feat(PAYMENTS-16663): add credit card integration example
xsolla/pay-station-sdk pull request #44
Opened 2023-11-03 11:09 UTC by zaslavskij

2023-11-07 07:09 UTC, gazaret requested changes

2023-11-07 07:09 UTC, gazaret commented on examples/credit-card/script.js
> +      if (nextAction.type === 'check_status') {
i don't see 3ds flow :(

2023-11-07 07:11 UTC, gazaret commented on examples/credit-card/index.html
> +<!doctype html>
also we should check readme.md, it's actual?

2023-11-07 12:22 UTC, simbirromanmakarov commented on examples/credit-card/return.js
> +  const accessToken = 'qnntUAwBk6NOUTuIojHW3pRJvFuXwJaI_lc_ru';
го, удалим токены из примера?

2023-11-07 12:22 UTC, simbirromanmakarov commented on examples/credit-card/script.js
> +  const accessToken = 'qnnt5fkqQjvxM34SoMXR4sVpSOEZFg0H_lc_ru';
и здесь

2023-11-07 12:25 UTC, simbirromanmakarov commented on examples/credit-card/init-payment-flow.js
> +      returnUrl: '/',
кажется headlessCheckout не принимает returnUrl, мы его в при инициализации формы передаем

2023-11-07 12:26 UTC, simbirromanmakarov commented on examples/credit-card/init-payment-flow.js
> +      if (nextAction.type === 'show_fields') {
может switch?

2023-11-08 04:36 UTC, simbirromanmakarov commented on examples/credit-card/return.js
> +      isWebview: false,
`V` большая в `isWebView`
![image](https://github.com/xsolla/pay-station-sdk/assets/133950148/a45344e0-57da-496d-97e6-9d5c7765aff4)

2023-11-08 09:40 UTC, gazaret approved these changes

2023-11-10 07:48 UTC, merged